In [6]:
# Task 1:

import numpy as np

# 1. Create arrays
array_1d = np.arange(1, 11)
array_2d = np.arange(1, 10).reshape(3, 3)
array_3d = np.random.random((3, 5, 3))

# 2. Display shape, size, and data type of each array
print("1D Array:")
print(array_1d)
print(f"Shape: {array_1d.shape}, Size: {array_1d.size}, Data type: {array_1d.dtype}\n")

print("2D Array:")
print(array_2d)
print(f"Shape: {array_2d.shape}, Size: {array_2d.size}, Data type: {array_2d.dtype}\n")

print("3D Array:")
print(array_3d)
print(f"Shape: {array_3d.shape}, Size: {array_3d.size}, Data type: {array_3d.dtype}")


1D Array:
[ 1  2  3  4  5  6  7  8  9 10]
Shape: (10,), Size: 10, Data type: int32

2D Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Shape: (3, 3), Size: 9, Data type: int32

3D Array:
[[[0.89139445 0.02491865 0.60882433]
  [0.79097494 0.99454045 0.10585927]
  [0.19916823 0.95355412 0.43584159]
  [0.01196941 0.01343623 0.37255312]
  [0.68497698 0.94340341 0.00187502]]

 [[0.30176876 0.07756523 0.72688666]
  [0.92448606 0.5072823  0.0081353 ]
  [0.16687708 0.79405024 0.07177209]
  [0.26232197 0.31649497 0.66709247]
  [0.4635448  0.48320709 0.08837408]]

 [[0.06407093 0.38444225 0.34196449]
  [0.9238853  0.86092274 0.21301676]
  [0.33656618 0.18666851 0.10592636]
  [0.62874601 0.68108457 0.90250236]
  [0.24207844 0.8216656  0.01665534]]]
Shape: (3, 5, 3), Size: 45, Data type: float64


In [3]:
# Task 2:
# 1. Create the NumPy array
data = [10, 20, 30, 40, 50, 60, 70, 80, 90]
array = np.array(data)

# 2. Perform required slicing operations
first_three = array[:3]
alternate_elements = array[::2]
reversed_array = array[::-1]

print("Original Array:",array)
print("\nFirst three elements:",first_three)
print("\nEvery alternate element:",alternate_elements)
print("\nReversed array:",reversed_array)



Original Array: [10 20 30 40 50 60 70 80 90]

First three elements: [10 20 30]

Every alternate element: [10 30 50 70 90]

Reversed array: [90 80 70 60 50 40 30 20 10]


In [10]:
# Task 3:

A = np.random.randint(1, 21, 5)
B = np.random.randint(1, 21, 5)
print("Array A:", A)
print("Array B:", B)

print("\nAddition:", A + B)
print("Subtraction:", A - B)
print("Multiplication:", A * B)
print("Division:", A / B)

dot_product = np.dot(A, B)
print("\nDot Product:", dot_product)

print("Mean A:", np.mean(A))
print("Median A:", np.median(A))
print("Standard Deviation A:", np.std(A))
print("Variance A:", np.var(A))

max_value = np.max(B)
min_value = np.min(B)
max_index = np.argmax(B)
min_index = np.argmin(B)

print("\nMax B:", max_value, "at index", max_index)
print("Min B:", min_value, "at index", min_index)


Array A: [10 14  8  4 11]
Array B: [15  9 16 12  9]

Addition: [25 23 24 16 20]
Subtraction: [-5  5 -8 -8  2]
Multiplication: [150 126 128  48  99]
Division: [0.66666667 1.55555556 0.5        0.33333333 1.22222222]

Dot Product: 551
Mean A: 9.4
Median A: 10.0
Standard Deviation A: 3.32264954516723
Variance A: 11.040000000000001

Max B: 16 at index 2
Min B: 9 at index 1


In [14]:
# Task 4:

array_1d = np.arange(1, 13)
print("Original Array:",array_1d)

# Reshape
array_2d = array_1d.reshape(4, 3)
print("\nReshaped to 2D (4x3):",array_2d)

array_3d = array_1d.reshape(2, 2, 3)
print("\nReshaped to 3D (2x2x3):",array_3d)

# Transpose
array_2d_transposed = array_2d.T
print("\nTranspose",array_2d_transposed)
print("Transpose Shape:", array_2d_transposed.shape)


Original Array: [ 1  2  3  4  5  6  7  8  9 10 11 12]

Reshaped to 2D (4x3): [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

Reshaped to 3D (2x2x3): [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]

Transpose [[ 1  4  7 10]
 [ 2  5  8 11]
 [ 3  6  9 12]]
Transpose Shape: (3, 4)


In [16]:
# Task 5:
# Boolean Masking and Filtering 

array = np.random.randint(10, 51, 15)
print("Original Array:",array)

greater_than_25 = array[array > 25]
print("\nElements greater than 25:",greater_than_25)

modified_array = array.copy()
modified_array[modified_array < 30] = 0
print("\nArray after replacing elements < 30 with 0:",modified_array)

div_by_5_count = np.sum(array % 5 == 0)
print("\nNumber of elements divisible by 5:", div_by_5_count)


Original Array: [19 28 21 30 26 21 20 32 32 39 26 18 36 19 36]

Elements greater than 25: [28 30 26 32 32 39 26 36 36]

Array after replacing elements < 30 with 0: [ 0  0  0 30  0  0  0 32 32 39  0  0 36  0 36]

Number of elements divisible by 5: 2


In [18]:
# Task 6: Working with Built-in Functions 

linspace_arr = np.linspace(0, 1, 10)

identity_mat = np.eye(4)       

rand_ints = np.random.randint(1, 101, size=20)
sorted_ints = np.sort(rand_ints)    
largest_five = sorted_ints[-5:]           

print("10 equally spaced values between 0 and 1:",linspace_arr)
print("4×4 Identity matrix:",identity_mat)
print("Random integers :",rand_ints)
print("\nSorted integers:",sorted_ints)
print("\nFive largest integers:",largest_five)



10 equally spaced values between 0 and 1: [0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]
4×4 Identity matrix: [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
Random integers : [16 58 62 59 15 49 90 12 93 68 66  7 38 48 10 78 44 53 41 41]

Sorted integers: [ 7 10 12 15 16 38 41 41 44 48 49 53 58 59 62 66 68 78 90 93]

Five largest integers: [66 68 78 90 93]


In [19]:
# Task 7: Generic 

import time
np.random.seed(0)  
A = np.random.rand(100, 100)
B = np.random.rand(100, 100)

start_time = time.time()

C = np.dot(A, B)

try:
    determinant = np.linalg.det(C)
    inverse = np.linalg.inv(C)
    print("Determinant of the result matrix:", determinant)
    print("Inverse calculated successfully.")
except np.linalg.LinAlgError:
    print("Matrix is singular, inverse cannot be computed.")
    determinant = None
    inverse = None

# Measure end time
end_time = time.time()
elapsed_time = end_time - start_time
print(f"\nTime taken for matrix multiplication, determinant and inversion: {elapsed_time:.4f} seconds")


Determinant of the result matrix: 6.01585369597092e+50
Inverse calculated successfully.

Time taken for matrix multiplication, determinant and inversion: 0.0789 seconds
